export const ATTENDANCE_INTIME_REQUEST = "ATTENDANCE_INTIME_REQUEST";
export const ATTENDANCE_INTIME_SUCCESS = "ATTENDANCE_INTIME_SUCCESS";
export const ATTENDANCE_INTIME_FAIL = "ATTENDANCE_INTIME_FAIL";
export const ATTENDANCE_INTIME_RESET = "ATTENDANCE_INTIME_RESET";

export const ATTENDANCE_OUTTIME_REQUEST = "ATTENDANCE_OUTTIME_REQUEST";
export const ATTENDANCE_OUTTIME_SUCCESS = "ATTENDANCE_OUTTIME_SUCCESS";
export const ATTENDANCE_OUTTIME_FAIL = "ATTENDANCE_OUTTIME_FAIL";
export const ATTENDANCE_OUTTIME_RESET = "ATTENDANCE_OUTTIME_RESET";

export const ATTENDANCE_Break1InTime_REQUEST =
  "ATTENDANCE_Break1InTime_REQUEST";
export const ATTENDANCE_Break1InTime_SUCCESS =
  "ATTENDANCE_Break1InTime_SUCCESS";
export const ATTENDANCE_Break1InTime_FAIL = "ATTENDANCE_Break1InTime_FAIL";
export const ATTENDANCE_Break1InTime_RESET = "ATTENDANCE_Break1InTime_RESET";

export const MANUAL_ATTENDANCE_REQUEST = "MANUAL_ATTENDANCE_REQUEST";
export const MANUAL_ATTENDANCE_SUCCESS = "MANUAL_ATTENDANCE_SUCCESS";
export const MANUAL_ATTENDANCE_FAIL = "MANUAL_ATTENDANCE_FAIL";
export const MANUAL_ATTENDANCE_RESET = "MANUAL_ATTENDANCE_RESET";

export const MANUAL_ATTENDANCE_REQUEST_REQUEST =
  "MANUAL_ATTENDANCE_REQUEST_REQUEST";
export const MANUAL_ATTENDANCE_REQUEST_SUCCESS =
  "MANUAL_ATTENDANCE_REQUEST_SUCCESS";
export const MANUAL_ATTENDANCE_REQUEST_FAIL = "MANUAL_ATTENDANCE_REQUEST_FAIL";
export const MANUAL_ATTENDANCE_REQUEST_RESET =
  "MANUAL_ATTENDANCE_REQUEST_RESET";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";

export const PENDING_ATTENDANCE_REQUEST_REQUEST =
  "PENDING_ATTENDANCE_REQUEST_REQUEST";
export const PENDING_ATTENDANCE_REQUEST_SUCCESS =
  "PENDING_ATTENDANCE_REQUEST_SUCCESS";
export const PENDING_ATTENDANCE_REQUEST_FAIL =
  "PENDING_ATTENDANCE_REQUEST_FAIL";
export const PENDING_ATTENDANCE_REQUEST_RESET =
  "PENDING_ATTENDANCE_REQUEST_RESET";

export const PENDING_ATTENDANCE_DELETE_REQUEST =
  "PENDING_ATTENDANCE_DELETE_REQUEST";
export const PENDING_ATTENDANCE_DELETE_SUCCESS =
  "PENDING_ATTENDANCE_DELETE_SUCCESS";
export const PENDING_ATTENDANCE_DELETE_FAIL = "PENDING_ATTENDANCE_DELETE_FAIL";
export const PENDING_ATTENDANCE_DELETE_RESET =
  "PENDING_ATTENDANCE_DELETE_RESET";

export const PENDING_ATTENDANCE_DETAIL_REQUEST_REQUEST =
  "PENDING_ATTENDANCE_REQUEST_REQUEST";
export const PENDING_ATTENDANCE_DETAIL_REQUEST_SUCCESS =
  "PENDING_ATTENDANCE_REQUEST_SUCCESS";
export const PENDING_ATTENDANCE_DETAIL_REQUEST_FAIL =
  "PENDING_ATTENDANCE_REQUEST_FAIL";
export const PENDING_ATTENDANCE_DETAIL_REQUEST_RESET =
  "PENDING_ATTENDANCE_REQUEST_RESET";

export const ATTENDANCE_Break1OutTime_REQUEST =
  "ATTENDANCE_Break1OutTime_REQUEST";
export const ATTENDANCE_Break1OutTime_SUCCESS =
  "ATTENDANCE_Break1OutTime_SUCCESS";
export const ATTENDANCE_Break1OutTime_FAIL = "ATTENDANCE_Break1OutTime_FAIL";
export const ATTENDANCE_Break1OutTime_RESET = "ATTENDANCE_Break1OutTime_RESET";

export const ATTENDANCE_Break2InTime_REQUEST =
  "ATTENDANCE_Break2InTime_REQUEST";
export const ATTENDANCE_Break2InTime_SUCCESS =
  "ATTENDANCE_Break2InTime_SUCCESS";
export const ATTENDANCE_Break2InTime_FAIL = "ATTENDANCE_Break2InTime_FAIL";
export const ATTENDANCE_Break2InTime_RESET = "ATTENDANCE_Break2InTime_RESET";

export const ATTENDANCE_Break2OutTime_REQUEST =
  "ATTENDANCE_Break2OutTime_REQUEST";
export const ATTENDANCE_Break2OutTime_SUCCESS =
  "ATTENDANCE_Break2OutTime_SUCCESS";
export const ATTENDANCE_Break2OutTime_FAIL = "ATTENDANCE_Break2OutTime_FAIL";
export const ATTENDANCE_Break2OutTime_RESET = "ATTENDANCE_Break2OutTime_RESET";

export const STAFF_ATTENDANCE_REQUEST = "STAFF_ATTENDANCE_REQUEST";
export const STAFF_ATTENDANCE_SUCCESS = "STAFF_ATTENDANCE_SUCCESS";
export const STAFF_ATTENDANCE_FAIL = "STAFF_ATTENDANCE_FAIL";
export const STAFF_ATTENDANCE_RESET = "STAFF_ATTENDANCE_RESET";

export const ATTENDANCE_DELETE_REQUEST = "ATTENDANCE_DELETE_REQUEST";
export const ATTENDANCE_DELETE_SUCCESS = "ATTENDANCE_DELETE_SUCCESS";
export const ATTENDANCE_DELETE_FAIL = "ATTENDANCE_DELETE_FAIL";
export const ATTENDANCE_DELETE_RESET = "ATTENDANCE_DELETE_RESET";

export const ATTENDANCE_UPDATE_REQUEST = "ATTENDANCE_UPDATE_REQUEST";
export const ATTENDANCE_UPDATE_SUCCESS = "ATTENDANCE_UPDATE_SUCCESS";
export const ATTENDANCE_UPDATE_FAIL = "ATTENDANCE_UPDATE_FAIL";
export const ATTENDANCE_UPDATE_RESET = "ATTENDANCE_UPDATE_RESET";

export const ATTENDANCE_DETAIL_REQUEST = "ATTENDANCE_DETAIL_REQUEST";
export const ATTENDANCE_DETAIL_SUCCESS = "ATTENDANCE_DETAIL_SUCCESS";
export const ATTENDANCE_DETAIL_FAIL = "ATTENDANCE_DETAIL_FAIL";
export const ATTENDANCE_DETAIL_RESET = "ATTENDANCE_DETAIL_RESET";
export const ADMIN_ATTENDANCE_RESET = "ADMIN_ATTENDANCE_RESET";
