export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_lOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const USER_ATTENDANCE_REQUEST = "USER_ATTENDANCE_REQUEST";
export const ADMIN_ATTENDANCE_REQUEST = "ADMIN_ATTENDANCE_REQUEST";
export const ATTENDANCE_REQUEST = "ATTENDANCE_REQUEST";
export const USER_ATTENDANCE_SUCCESS = "USER_ATTENDANCE_SUCCESS";
export const ADMIN_ATTENDANCE_SUCCESS = "ADMIN_ATTENDANCE_SUCCESS";
export const ATTENDANCE_REQUEST_SUCCESS = "ATTENDANCE_REQUEST_SUCCESS";
export const USER_ATTENDANCE_FAIL = "USER_ATTENDANCE_FAIL";
export const ADMIN_ATTENDANCE_FAIL = "ADMIN_ATTENDANCE_FAIL";
export const ATTENDANCE_REQUEST_FAIL = "ATTENDANCE_REQUEST_FAIL";
export const USER_ATTENDANCE_RESET = "USER_ATTENDANCE_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";
export const USER_DETAIL_RESET = "USER_DETAIL_RESET";

export const DEPARTMENT_LIST = "DEPARTMENT_LIST";
export const DEPARTMENT_FAIL = "DEPARTMENT_FAIL";
export const DEPARTMENT_SUCCESS = "DEPARTMENT_SUCCESS";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";
export const USER_DELETE_RESET = "USER_DELETE_RESET";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const UPDATE_PASSWORD_REQUEST = "USER_UPDATE_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "USER_UPDATE_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "USER_UPDATE_FAIL";
export const UPDATE_PASSWORD_RESET = "USER_UPDATE_RESET";
